In [50]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [51]:
train = pd.read_csv("train.csv")
public_test = pd.read_csv("public_test.csv")
private_test = pd.read_csv("private_test.csv")

In [52]:
train.head()

,User_ID,Age,Income,City_Tier,Device_Type,Traffic_Source,Pages_Viewed,Products_Viewed,Time_On_Site,Previous_Purchases,Discount_Seen,Browser_Version,Campaign_Code,Converted
0,1,58.0,103593.708812,2,Mobile,Organic,5,4,9.61,3,0,11,2418,0
1,2,26.0,36451.716984,2,Mobile,Social Media,11,3,17.63,2,0,14,1213,0
2,3,19.0,30511.228700,3,Mobile,Referral,1,1,13.25,5,0,5,2849,0
3,4,48.0,87789.172342,3,Mobile,Email,14,12,NaN,1,1,19,7610,0
4,5,35.0,105229.249067,2,Mobile,Social Media,14,21,16.92,1,0,5,9261,0

In [53]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   User_ID             10000 non-null  int64
 1   Age                 8520 non-null   float64
 2   Income              9016 non-null   float64
 3   City_Tier           10000 non-null  int64
 4   Device_Type         10000 non-null  str
 5   Traffic_Source      10000 non-null  str
 6   Pages_Viewed        10000 non-null  int64
 7   Products_Viewed     10000 non-null  int64
 8   Time_On_Site        8152 non-null   float64
 9   Previous_Purchases  10000 non-null  int64
 10  Discount_Seen       10000 non-null  int64
 11  Browser_Version     10000 non-null  int64
 12  Campaign_Code       10000 non-null  int64
 13  Converted           10000 non-null  int64
dtypes: float64(3), int64(9), str(2)
memory usage: 1.1 MB

In [54]:
train.describe()

,User_ID,Age,Income,City_Tier,Pages_Viewed,Products_Viewed,Time_On_Site,Previous_Purchases,Discount_Seen,Browser_Version,Campaign_Code,Converted
count,10000.00000,8520.000000,9016.000000,10000.000000,10000.00000,10000.000000,8152.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,41.457746,69961.772797,1.933400,15.60850,15.219300,13.667241,2.972500,0.540700,12.473900,5511.162200,0.30870
std,2886.89568,13.770164,24790.673822,0.737712,8.62346,8.927563,19.438244,1.738691,0.498366,6.892856,2596.933802,0.46198
min,1.00000,18.000000,12000.000000,1.000000,1.00000,1.000000,0.800000,0.000000,0.000000,1.000000,1000.000000,0.00000
25%,2500.75000,29.000000,52294.644359,1.000000,8.00000,8.000000,7.640000,2.000000,0.000000,7.000000,3251.750000,0.00000
50%,5000.50000,41.000000,70171.613672,2.000000,16.00000,15.000000,11.145000,3.000000,1.000000,12.000000,5515.500000,0.00000
75%,7500.25000,53.000000,86907.747154,2.000000,23.00000,23.000000,15.630000,4.000000,1.000000,18.000000,7759.000000,1.00000
max,10000.00000,65.000000,161687.774167,3.000000,30.00000,37.000000,607.390000,12.000000,1.000000,24.000000,9998.000000,1.00000

In [55]:
train.isnull().sum()

User_ID                  0
Age                   1480
Income                 984
City_Tier                0
Device_Type              0
Traffic_Source           0
Pages_Viewed             0
Products_Viewed          0
Time_On_Site          1848
Previous_Purchases       0
Discount_Seen            0
Browser_Version          0
Campaign_Code            0
Converted                0
dtype: int64

In [57]:
train.sort_values(by='User_ID',inplace=True)

In [58]:
train.head()

,User_ID,Age,Income,City_Tier,Device_Type,Traffic_Source,Pages_Viewed,Products_Viewed,Time_On_Site,Previous_Purchases,Discount_Seen,Browser_Version,Campaign_Code,Converted
0,1,58.0,103593.708812,2,Mobile,Organic,5,4,9.61,3,0,11,2418,0
1,2,26.0,36451.716984,2,Mobile,Social Media,11,3,17.63,2,0,14,1213,0
2,3,19.0,30511.228700,3,Mobile,Referral,1,1,13.25,5,0,5,2849,0
3,4,48.0,87789.172342,3,Mobile,Email,14,12,NaN,1,1,19,7610,0
4,5,35.0,105229.249067,2,Mobile,Social Media,14,21,16.92,1,0,5,9261,0

In [59]:
train['Device_Type'].value_counts()

Device_Type
Mobile     6523
Desktop    2472
Tablet     1005
Name: count, dtype: int64

In [60]:
train['City_Tier'].value_counts()

City_Tier
2    4514
1    3076
3    2410
Name: count, dtype: int64

In [61]:
train['Campaign_Code'].duplicated().value_counts()

Campaign_Code
False    6014
True     3986
Name: count, dtype: int64

In [62]:
train[(train["Converted"] == 1) & (train["Time_On_Site"].isnull())].shape[0]

467

In [63]:
train[(train["Converted"] == 0) & (train["Time_On_Site"].isnull())].shape[0]

1381

In [64]:
train[(train["Previous_Purchases"] >0) & (train["Time_On_Site"].isnull())].shape[0]

1745

In [65]:
train[(train["Products_Viewed"] >3) & (train["Time_On_Site"].isnull())].shape[0]

1635

In [66]:
train["Time_On_Site"].shape

(10000,)

In [67]:
train["Age"].isna().sum()

np.int64(1480)

In [68]:
train

,User_ID,Age,Income,City_Tier,Device_Type,Traffic_Source,Pages_Viewed,Products_Viewed,Time_On_Site,Previous_Purchases,Discount_Seen,Browser_Version,Campaign_Code,Converted
0,1,58.0,103593.708812,2,Mobile,Organic,5,4,9.61,3,0,11,2418,0
1,2,26.0,36451.716984,2,Mobile,Social Media,11,3,17.63,2,0,14,1213,0
2,3,19.0,30511.228700,3,Mobile,Referral,1,1,13.25,5,0,5,2849,0
3,4,48.0,87789.172342,3,Mobile,Email,14,12,NaN,1,1,19,7610,0
4,5,35.0,105229.249067,2,Mobile,Social Media,14,21,16.92,1,0,5,9261,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,65.0,90204.794616,1,Mobile,Organic,9,9,4.67,5,0,6,8293,0
9996,9997,53.0,93283.066383,1,Mobile,Organic,22,21,NaN,3,1,23,9175,1
9997,9998,49.0,75347.420328,2,Desktop,Paid Ads,19,19,5.18,1,1,4,9709,0
9998,9999,51.0,59311.028526,2,Mobile,Organic,15,13,5.67,1,1,1,2449,1
9999,10000,60.0,61969.931987,2,Mobile,Paid Ads,25,22,22.22,4,0,7,7941,0

In [69]:
train.isnull().sum()

User_ID                  0
Age                   1480
Income                 984
City_Tier                0
Device_Type              0
Traffic_Source           0
Pages_Viewed             0
Products_Viewed          0
Time_On_Site          1848
Previous_Purchases       0
Discount_Seen            0
Browser_Version          0
Campaign_Code            0
Converted                0
dtype: int64

In [70]:
train['Age'].var()

np.float64(189.61741856231885)

In [71]:
train.isnull().sum()

User_ID                  0
Age                   1480
Income                 984
City_Tier                0
Device_Type              0
Traffic_Source           0
Pages_Viewed             0
Products_Viewed          0
Time_On_Site          1848
Previous_Purchases       0
Discount_Seen            0
Browser_Version          0
Campaign_Code            0
Converted                0
dtype: int64

In [72]:
imputer=SimpleImputer(strategy="median")

In [73]:
train[['Age','Income','Time_On_Site']]=imputer.fit_transform(train[['Age','Income','Time_On_Site']])

In [74]:
train

,User_ID,Age,Income,City_Tier,Device_Type,Traffic_Source,Pages_Viewed,Products_Viewed,Time_On_Site,Previous_Purchases,Discount_Seen,Browser_Version,Campaign_Code,Converted
0,1,58.0,103593.708812,2,Mobile,Organic,5,4,9.610,3,0,11,2418,0
1,2,26.0,36451.716984,2,Mobile,Social Media,11,3,17.630,2,0,14,1213,0
2,3,19.0,30511.228700,3,Mobile,Referral,1,1,13.250,5,0,5,2849,0
3,4,48.0,87789.172342,3,Mobile,Email,14,12,11.145,1,1,19,7610,0
4,5,35.0,105229.249067,2,Mobile,Social Media,14,21,16.920,1,0,5,9261,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,65.0,90204.794616,1,Mobile,Organic,9,9,4.670,5,0,6,8293,0
9996,9997,53.0,93283.066383,1,Mobile,Organic,22,21,11.145,3,1,23,9175,1
9997,9998,49.0,75347.420328,2,Desktop,Paid Ads,19,19,5.180,1,1,4,9709,0
9998,9999,51.0,59311.028526,2,Mobile,Organic,15,13,5.670,1,1,1,2449,1
9999,10000,60.0,61969.931987,2,Mobile,Paid Ads,25,22,22.220,4,0,7,7941,0

In [75]:
private_test.shape

(3000, 13)

In [76]:
private_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   User_ID             3000 non-null   int64
 1   Age                 2539 non-null   float64
 2   Income              2698 non-null   float64
 3   City_Tier           3000 non-null   int64
 4   Device_Type         3000 non-null   str
 5   Traffic_Source      3000 non-null   str
 6   Pages_Viewed        3000 non-null   int64
 7   Products_Viewed     3000 non-null   int64
 8   Time_On_Site        2438 non-null   float64
 9   Previous_Purchases  3000 non-null   int64
 10  Discount_Seen       3000 non-null   int64
 11  Browser_Version     3000 non-null   int64
 12  Campaign_Code       3000 non-null   int64
dtypes: float64(3), int64(8), str(2)
memory usage: 304.8 KB

In [77]:
private_test.describe()

,User_ID,Age,Income,City_Tier,Pages_Viewed,Products_Viewed,Time_On_Site,Previous_Purchases,Discount_Seen,Browser_Version,Campaign_Code
count,3000.000000,2539.000000,2698.000000,3000.00000,3000.000000,3000.000000,2438.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,104500.500000,41.282001,70249.499155,1.95600,15.428667,15.008000,13.932974,2.959333,0.546333,12.341333,5519.437667
std,866.169729,13.687726,24802.551359,0.73773,8.708857,8.963856,22.061855,1.711721,0.497932,6.879966,2607.466173
min,103001.000000,18.000000,12000.000000,1.00000,1.000000,1.000000,0.380000,0.000000,0.000000,1.000000,1006.000000
25%,103750.750000,30.000000,53053.114312,1.00000,8.000000,7.000000,7.570000,2.000000,0.000000,6.000000,3245.500000
50%,104500.500000,42.000000,70465.721888,2.00000,15.000000,15.000000,10.880000,3.000000,1.000000,12.000000,5539.000000
75%,105250.250000,53.000000,87367.487425,3.00000,23.000000,22.250000,15.087500,4.000000,1.000000,18.000000,7711.250000
max,106000.000000,65.000000,181292.643570,3.00000,30.000000,37.000000,363.570000,10.000000,1.000000,24.000000,9995.000000

In [78]:
private_test['Income'].median()

np.float64(70465.72188799037)

In [79]:
private_test[['Age','Income','Time_On_Site']]=imputer.fit_transform(private_test[['Age','Income','Time_On_Site']])

In [80]:
public_test.describe()

,User_ID,Age,Income,City_Tier,Pages_Viewed,Products_Viewed,Time_On_Site,Previous_Purchases,Discount_Seen,Browser_Version,Campaign_Code,Converted
count,3000.000000,2528.000000,2699.000000,3000.000000,3000.000000,3000.000000,2432.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,101500.500000,41.660997,71103.390196,1.939333,15.378333,15.028000,13.780859,3.036000,0.550333,12.636333,5504.309333,0.295333
std,866.169729,14.030755,24469.813897,0.755321,8.708682,9.045873,21.283364,1.723667,0.497543,6.973351,2568.659082,0.456269
min,100001.000000,18.000000,12000.000000,1.000000,1.000000,1.000000,0.590000,0.000000,0.000000,1.000000,1003.000000,0.000000
25%,100750.750000,29.000000,53953.872038,1.000000,8.000000,7.000000,7.627500,2.000000,0.000000,7.000000,3299.250000,0.000000
50%,101500.500000,42.000000,70947.845512,2.000000,15.000000,15.000000,11.130000,3.000000,1.000000,13.000000,5493.000000,0.000000
75%,102250.250000,54.000000,88276.370022,3.000000,23.000000,23.000000,15.752500,4.000000,1.000000,19.000000,7675.250000,1.000000
max,103000.000000,65.000000,145218.173839,3.000000,30.000000,37.000000,431.100000,10.000000,1.000000,24.000000,9997.000000,1.000000

In [81]:
public_test[['Age','Income','Time_On_Site']]=imputer.fit_transform(public_test[['Age','Income','Time_On_Site']])

In [82]:
train.head()

,User_ID,Age,Income,City_Tier,Device_Type,Traffic_Source,Pages_Viewed,Products_Viewed,Time_On_Site,Previous_Purchases,Discount_Seen,Browser_Version,Campaign_Code,Converted
0,1,58.0,103593.708812,2,Mobile,Organic,5,4,9.610,3,0,11,2418,0
1,2,26.0,36451.716984,2,Mobile,Social Media,11,3,17.630,2,0,14,1213,0
2,3,19.0,30511.228700,3,Mobile,Referral,1,1,13.250,5,0,5,2849,0
3,4,48.0,87789.172342,3,Mobile,Email,14,12,11.145,1,1,19,7610,0
4,5,35.0,105229.249067,2,Mobile,Social Media,14,21,16.920,1,0,5,9261,0

In [83]:
train['Engagement_Score']=(train['Pages_Viewed']+train['Products_Viewed']+train['Time_On_Site'])
private_test['Engagement_Score']=(private_test['Pages_Viewed']+private_test['Products_Viewed']+private_test['Time_On_Site'])
public_test['Engagement_Score']=(public_test['Pages_Viewed']+public_test['Products_Viewed']+public_test['Time_On_Site'])

In [84]:
train.drop(['Pages_Viewed','Products_Viewed','Time_On_Site',],axis=1,inplace=True)
private_test.drop(['Pages_Viewed','Products_Viewed','Time_On_Site',],axis=1,inplace=True)
public_test.drop(['Pages_Viewed','Products_Viewed','Time_On_Site',],axis=1,inplace=True)

In [85]:
train

,User_ID,Age,Income,City_Tier,Device_Type,Traffic_Source,Previous_Purchases,Discount_Seen,Browser_Version,Campaign_Code,Converted,Engagement_Score
0,1,58.0,103593.708812,2,Mobile,Organic,3,0,11,2418,0,18.610
1,2,26.0,36451.716984,2,Mobile,Social Media,2,0,14,1213,0,31.630
2,3,19.0,30511.228700,3,Mobile,Referral,5,0,5,2849,0,15.250
3,4,48.0,87789.172342,3,Mobile,Email,1,1,19,7610,0,37.145
4,5,35.0,105229.249067,2,Mobile,Social Media,1,0,5,9261,0,51.920
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,65.0,90204.794616,1,Mobile,Organic,5,0,6,8293,0,22.670
9996,9997,53.0,93283.066383,1,Mobile,Organic,3,1,23,9175,1,54.145
9997,9998,49.0,75347.420328,2,Desktop,Paid Ads,1,1,4,9709,0,43.180
9998,9999,51.0,59311.028526,2,Mobile,Organic,1,1,1,2449,1,33.670
9999,10000,60.0,61969.931987,2,Mobile,Paid Ads,4,0,7,7941,0,69.220

In [37]:
train.drop(['User_ID'],axis=1,inplace=True)
private_test.drop(['User_ID'],axis=1,inplace=True)
public_test.drop(['User_ID'],axis=1,inplace=True)

In [38]:
train['Device_Traffic']=(train['Device_Type']+train['Traffic_Source'])
private_test['Device_Traffic']=(private_test['Device_Type']+private_test['Traffic_Source'])
public_test['Device_Traffic']=(public_test['Device_Type']+public_test['Traffic_Source'])

In [39]:
train.drop(['Device_Type','Traffic_Source'],axis=1,inplace=True)
private_test.drop(['Device_Type','Traffic_Source'],axis=1,inplace=True)
public_test.drop(['Device_Type','Traffic_Source'],axis=1,inplace=True)

In [116]:
train

,Age,Income,City_Tier,Previous_Purchases,Discount_Seen,Browser_Version,Campaign_Code,Converted,Engagement_Score,Device_Traffic
0,58.0,103593.708812,2,3,0,11,2418,0,18.610,MobileOrganic
1,26.0,36451.716984,2,2,0,14,1213,0,31.630,MobileSocial Media
2,19.0,30511.228700,3,5,0,5,2849,0,15.250,MobileReferral
3,48.0,87789.172342,3,1,1,19,7610,0,37.145,MobileEmail
4,35.0,105229.249067,2,1,0,5,9261,0,51.920,MobileSocial Media
...,...,...,...,...,...,...,...,...,...,...
9995,65.0,90204.794616,1,5,0,6,8293,0,22.670,MobileOrganic
9996,53.0,93283.066383,1,3,1,23,9175,1,54.145,MobileOrganic
9997,49.0,75347.420328,2,1,1,4,9709,0,43.180,DesktopPaid Ads
9998,51.0,59311.028526,2,1,1,1,2449,1,33.670,MobileOrganic
9999,60.0,61969.931987,2,4,0,7,7941,0,69.220,MobilePaid Ads

In [40]:
train['previous_customer'] = (train['Previous_Purchases'] > 0).astype(int)
private_test['previous_customer'] = (private_test['Previous_Purchases'] > 0).astype(int)
public_test['previous_customer'] = (public_test['Previous_Purchases'] > 0).astype(int)

In [41]:
train

,Age,Income,City_Tier,Previous_Purchases,Discount_Seen,Browser_Version,Campaign_Code,Converted,Engagement_Score,Device_Traffic,previous_customer
0,58.0,103593.708812,2,3,0,11,2418,0,18.610,MobileOrganic,1
1,26.0,36451.716984,2,2,0,14,1213,0,31.630,MobileSocial Media,1
2,19.0,30511.228700,3,5,0,5,2849,0,15.250,MobileReferral,1
3,48.0,87789.172342,3,1,1,19,7610,0,37.145,MobileEmail,1
4,35.0,105229.249067,2,1,0,5,9261,0,51.920,MobileSocial Media,1
...,...,...,...,...,...,...,...,...,...,...,...
9995,65.0,90204.794616,1,5,0,6,8293,0,22.670,MobileOrganic,1
9996,53.0,93283.066383,1,3,1,23,9175,1,54.145,MobileOrganic,1
9997,49.0,75347.420328,2,1,1,4,9709,0,43.180,DesktopPaid Ads,1
9998,51.0,59311.028526,2,1,1,1,2449,1,33.670,MobileOrganic,1
9999,60.0,61969.931987,2,4,0,7,7941,0,69.220,MobilePaid Ads,1

In [42]:
train['previous_customer'].value_counts()

previous_customer
1    9467
0     533
Name: count, dtype: int64

In [86]:
train= pd.get_dummies(
    train,
    columns=['Device_Type', 'Traffic_Source'],
    drop_first=True,
    dtype=int
)
public_test= pd.get_dummies(
    public_test,
    columns=['Device_Type', 'Traffic_Source'],
    drop_first=True,
    dtype=int
)
private_test= pd.get_dummies(
    private_test,
    columns=['Device_Type', 'Traffic_Source'],
    drop_first=True,
    dtype=int
)

In [43]:
train.drop(['Previous_Purchases'],axis=1,inplace=True)
private_test.drop(['Previous_Purchases'],axis=1,inplace=True)
public_test.drop(['Previous_Purchases'],axis=1,inplace=True)

In [87]:
train

,User_ID,Age,Income,City_Tier,Previous_Purchases,Discount_Seen,Browser_Version,Campaign_Code,Converted,Engagement_Score,Device_Type_Mobile,Device_Type_Tablet,Traffic_Source_Organic,Traffic_Source_Paid Ads,Traffic_Source_Referral,Traffic_Source_Social Media
0,1,58.0,103593.708812,2,3,0,11,2418,0,18.610,1,0,1,0,0,0
1,2,26.0,36451.716984,2,2,0,14,1213,0,31.630,1,0,0,0,0,1
2,3,19.0,30511.228700,3,5,0,5,2849,0,15.250,1,0,0,0,1,0
3,4,48.0,87789.172342,3,1,1,19,7610,0,37.145,1,0,0,0,0,0
4,5,35.0,105229.249067,2,1,0,5,9261,0,51.920,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,65.0,90204.794616,1,5,0,6,8293,0,22.670,1,0,1,0,0,0
9996,9997,53.0,93283.066383,1,3,1,23,9175,1,54.145,1,0,1,0,0,0
9997,9998,49.0,75347.420328,2,1,1,4,9709,0,43.180,0,0,0,1,0,0
9998,9999,51.0,59311.028526,2,1,1,1,2449,1,33.670,1,0,1,0,0,0
9999,10000,60.0,61969.931987,2,4,0,7,7941,0,69.220,1,0,0,1,0,0

In [45]:
train['Device_Traffic']=train['Device_Traffic'].str.replace(' ','')
private_test['Device_Traffic']=private_test['Device_Traffic'].str.replace(' ','')
public_test['Device_Traffic']=public_test['Device_Traffic'].str.replace(' ','')

In [46]:
train

,Age,Income,City_Tier,Discount_Seen,Browser_Version,Campaign_Code,Converted,Engagement_Score,Device_Traffic,previous_customer
0,58.0,103593.708812,2,0,11,2418,0,18.610,MobileOrganic,1
1,26.0,36451.716984,2,0,14,1213,0,31.630,MobileSocialMedia,1
2,19.0,30511.228700,3,0,5,2849,0,15.250,MobileReferral,1
3,48.0,87789.172342,3,1,19,7610,0,37.145,MobileEmail,1
4,35.0,105229.249067,2,0,5,9261,0,51.920,MobileSocialMedia,1
...,...,...,...,...,...,...,...,...,...,...
9995,65.0,90204.794616,1,0,6,8293,0,22.670,MobileOrganic,1
9996,53.0,93283.066383,1,1,23,9175,1,54.145,MobileOrganic,1
9997,49.0,75347.420328,2,1,4,9709,0,43.180,DesktopPaidAds,1
9998,51.0,59311.028526,2,1,1,2449,1,33.670,MobileOrganic,1
9999,60.0,61969.931987,2,0,7,7941,0,69.220,MobilePaidAds,1

In [47]:
train.head()

,Age,Income,City_Tier,Discount_Seen,Browser_Version,Campaign_Code,Converted,Engagement_Score,Device_Traffic,previous_customer
0,58.0,103593.708812,2,0,11,2418,0,18.610,MobileOrganic,1
1,26.0,36451.716984,2,0,14,1213,0,31.630,MobileSocialMedia,1
2,19.0,30511.228700,3,0,5,2849,0,15.250,MobileReferral,1
3,48.0,87789.172342,3,1,19,7610,0,37.145,MobileEmail,1
4,35.0,105229.249067,2,0,5,9261,0,51.920,MobileSocialMedia,1

In [48]:
train.columns

Index(['Age', 'Income', 'City_Tier', 'Discount_Seen', 'Browser_Version',
       'Campaign_Code', 'Converted', 'Engagement_Score', 'Device_Traffic',
       'previous_customer'],
      dtype='str')

In [141]:
train

,Age,Income,City_Tier,Discount_Seen,Browser_Version,Campaign_Code,Converted,Engagement_Score,previous_customer,Device_Traffic_DesktopOrganic,...,Device_Traffic_MobileEmail,Device_Traffic_MobileOrganic,Device_Traffic_MobilePaidAds,Device_Traffic_MobileReferral,Device_Traffic_MobileSocialMedia,Device_Traffic_TabletEmail,Device_Traffic_TabletOrganic,Device_Traffic_TabletPaidAds,Device_Traffic_TabletReferral,Device_Traffic_TabletSocialMedia
0,58.0,103593.708812,2,0,11,2418,0,18.610,1,0,...,0,1,0,0,0,0,0,0,0,0
1,26.0,36451.716984,2,0,14,1213,0,31.630,1,0,...,0,0,0,0,1,0,0,0,0,0
2,19.0,30511.228700,3,0,5,2849,0,15.250,1,0,...,0,0,0,1,0,0,0,0,0,0
3,48.0,87789.172342,3,1,19,7610,0,37.145,1,0,...,1,0,0,0,0,0,0,0,0,0
4,35.0,105229.249067,2,0,5,9261,0,51.920,1,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,65.0,90204.794616,1,0,6,8293,0,22.670,1,0,...,0,1,0,0,0,0,0,0,0,0
9996,53.0,93283.066383,1,1,23,9175,1,54.145,1,0,...,0,1,0,0,0,0,0,0,0,0
9997,49.0,75347.420328,2,1,4,9709,0,43.180,1,0,...,0,0,0,0,0,0,0,0,0,0
9998,51.0,59311.028526,2,1,1,2449,1,33.670,1,0,...,0,1,0,0,0,0,0,0,0,0
9999,60.0,61969.931987,2,0,7,7941,0,69.220,1,0,...,0,0,1,0,0,0,0,0,0,0

In [142]:
private_test

,Age,Income,City_Tier,Discount_Seen,Browser_Version,Campaign_Code,Engagement_Score,previous_customer,Device_Traffic_DesktopOrganic,Device_Traffic_DesktopPaidAds,...,Device_Traffic_MobileEmail,Device_Traffic_MobileOrganic,Device_Traffic_MobilePaidAds,Device_Traffic_MobileReferral,Device_Traffic_MobileSocialMedia,Device_Traffic_TabletEmail,Device_Traffic_TabletOrganic,Device_Traffic_TabletPaidAds,Device_Traffic_TabletReferral,Device_Traffic_TabletSocialMedia
0,54.0,12000.000000,2,0,9,3685,17.14,1,0,0,...,1,0,0,0,0,0,0,0,0,0
1,59.0,70465.721888,3,0,18,9612,52.88,1,0,0,...,0,1,0,0,0,0,0,0,0,0
2,42.0,79296.908337,2,0,2,4522,55.36,1,0,0,...,0,0,1,0,0,0,0,0,0,0
3,19.0,65279.025663,2,1,5,4623,41.78,1,0,0,...,0,0,0,0,1,0,0,0,0,0
4,31.0,70465.721888,3,0,20,8663,49.14,1,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,32.0,75294.529879,2,0,12,1794,48.68,1,0,0,...,0,0,1,0,0,0,0,0,0,0
2996,30.0,86278.626308,3,1,11,4526,31.75,1,0,0,...,0,0,0,0,0,0,1,0,0,0
2997,53.0,76122.507493,2,1,24,9217,65.93,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2998,29.0,78503.583072,2,1,17,7176,75.11,1,0,0,...,0,0,0,0,1,0,0,0,0,0
2999,24.0,73100.416550,2,1,5,4124,60.33,1,0,0,...,0,0,0,1,0,0,0,0,0,0

In [144]:
train['Browser_Version'].nunique()

24

In [88]:
Scaler=StandardScaler()

In [89]:
train[['Income','Engagement_Score']]=Scaler.fit_transform(
    train[['Income','Engagement_Score']]
    )
private_test[['Income','Engagement_Score']]=Scaler.fit_transform(
    private_test[['Income','Engagement_Score']]
    )
public_test[['Income','Engagement_Score']]=Scaler.fit_transform(
    public_test[['Income','Engagement_Score']]
    )

In [148]:
train

,Age,Income,City_Tier,Discount_Seen,Browser_Version,Campaign_Code,Converted,Engagement_Score,previous_customer,Device_Traffic_DesktopOrganic,...,Device_Traffic_MobileEmail,Device_Traffic_MobileOrganic,Device_Traffic_MobilePaidAds,Device_Traffic_MobileReferral,Device_Traffic_MobileSocialMedia,Device_Traffic_TabletEmail,Device_Traffic_TabletOrganic,Device_Traffic_TabletPaidAds,Device_Traffic_TabletReferral,Device_Traffic_TabletSocialMedia
0,1.306775,1.427948,2,0,11,2418,0,-1.024641,1,0,...,0,1,0,0,0,0,0,0,0,0
1,-1.210792,-1.424525,2,0,14,1213,0,-0.499803,1,0,...,0,0,0,0,1,0,0,0,0,0
2,-1.761510,-1.676901,3,0,5,2849,0,-1.160084,1,0,...,0,0,0,1,0,0,0,0,0,0
3,0.520035,0.756505,3,1,19,7610,0,-0.277492,1,0,...,1,0,0,0,0,0,0,0,0,0
4,-0.502727,1.497433,2,0,5,9261,0,0.318090,1,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1.857492,0.859131,1,0,6,8293,0,-0.860982,1,0,...,0,1,0,0,0,0,0,0,0,0
9996,0.913405,0.989909,1,1,23,9175,1,0.407780,1,0,...,0,1,0,0,0,0,0,0,0,0
9997,0.598709,0.227928,2,1,4,9709,0,-0.034221,1,0,...,0,0,0,0,0,0,0,0,0,0
9998,0.756057,-0.453365,2,1,1,2449,1,-0.417570,1,0,...,0,1,0,0,0,0,0,0,0,0
9999,1.464123,-0.340404,2,0,7,7941,0,1.015456,1,0,...,0,0,1,0,0,0,0,0,0,0

In [151]:
scaled_cols_for_train = ['Age', 'Income', 'Engagement_Score']
# Inverse transform the three scaled columns from train
inverse_transformed_data = Scaler.inverse_transform(train[scaled_cols_for_train])

# Assign only the inverse transformed Age column back to train[['Age']]
train[['Age']] = inverse_transformed_data[:, 0].reshape(-1, 1)

In [154]:
train.drop('Age', axis=1, inplace=True)
private_test.drop('Age', axis=1, inplace=True)
public_test.drop('Age', axis=1, inplace=True)

In [155]:
train1=pd.read_csv('/content/train_imputed.csv')
private1=pd.read_csv('/content/private_test_imputed.csv')
public1=pd.read_csv('/content/public_test_imputed.csv')

In [158]:
train['Age']=train1['Age']
private_test['Age']=private1['Age']
public_test['Age']=public1['Age']

In [159]:
train

,Income,City_Tier,Discount_Seen,Browser_Version,Campaign_Code,Converted,Engagement_Score,previous_customer,Device_Traffic_DesktopOrganic,Device_Traffic_DesktopPaidAds,...,Device_Traffic_MobileOrganic,Device_Traffic_MobilePaidAds,Device_Traffic_MobileReferral,Device_Traffic_MobileSocialMedia,Device_Traffic_TabletEmail,Device_Traffic_TabletOrganic,Device_Traffic_TabletPaidAds,Device_Traffic_TabletReferral,Device_Traffic_TabletSocialMedia,Age
0,1.427948,2,0,11,2418,0,-1.024641,1,0,0,...,1,0,0,0,0,0,0,0,0,58.0
1,-1.424525,2,0,14,1213,0,-0.499803,1,0,0,...,0,0,0,1,0,0,0,0,0,26.0
2,-1.676901,3,0,5,2849,0,-1.160084,1,0,0,...,0,0,1,0,0,0,0,0,0,19.0
3,0.756505,3,1,19,7610,0,-0.277492,1,0,0,...,0,0,0,0,0,0,0,0,0,48.0
4,1.497433,2,0,5,9261,0,0.318090,1,0,0,...,0,0,0,1,0,0,0,0,0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.859131,1,0,6,8293,0,-0.860982,1,0,0,...,1,0,0,0,0,0,0,0,0,65.0
9996,0.989909,1,1,23,9175,1,0.407780,1,0,0,...,1,0,0,0,0,0,0,0,0,53.0
9997,0.227928,2,1,4,9709,0,-0.034221,1,0,1,...,0,0,0,0,0,0,0,0,0,49.0
9998,-0.453365,2,1,1,2449,1,-0.417570,1,0,0,...,1,0,0,0,0,0,0,0,0,51.0
9999,-0.340404,2,0,7,7941,0,1.015456,1,0,0,...,0,1,0,0,0,0,0,0,0,60.0

In [90]:
train

,User_ID,Age,Income,City_Tier,Previous_Purchases,Discount_Seen,Browser_Version,Campaign_Code,Converted,Engagement_Score,Device_Type_Mobile,Device_Type_Tablet,Traffic_Source_Organic,Traffic_Source_Paid Ads,Traffic_Source_Referral,Traffic_Source_Social Media
0,1,58.0,1.427948,2,3,0,11,2418,0,-1.024641,1,0,1,0,0,0
1,2,26.0,-1.424525,2,2,0,14,1213,0,-0.499803,1,0,0,0,0,1
2,3,19.0,-1.676901,3,5,0,5,2849,0,-1.160084,1,0,0,0,1,0
3,4,48.0,0.756505,3,1,1,19,7610,0,-0.277492,1,0,0,0,0,0
4,5,35.0,1.497433,2,1,0,5,9261,0,0.318090,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,65.0,0.859131,1,5,0,6,8293,0,-0.860982,1,0,1,0,0,0
9996,9997,53.0,0.989909,1,3,1,23,9175,1,0.407780,1,0,1,0,0,0
9997,9998,49.0,0.227928,2,1,1,4,9709,0,-0.034221,0,0,0,1,0,0
9998,9999,51.0,-0.453365,2,1,1,1,2449,1,-0.417570,1,0,1,0,0,0
9999,10000,60.0,-0.340404,2,4,0,7,7941,0,1.015456,1,0,0,1,0,0

In [91]:
X=train.drop('Converted',axis=1)
y=train['Converted']

In [92]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [93]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(max_iter=6000,
                      class_weight='balanced',
                      solver='liblinear',
                      C=0.5)
lr.fit(X_train,y_train)
y_pred =lr.predict(X_test)

In [94]:
from sklearn.metrics import f1_score
f1=f1_score(y_test,y_pred)

In [95]:
f1

0.5701058201058201

In [200]:
train[['Campaign_Code']]=Scaler.fit_transform(
    train[['Campaign_Code']]
    )
private_test[['Campaign_Code']]=Scaler.fit_transform(
    private_test[['Campaign_Code']]
    )
public_test[['Campaign_Code']]=Scaler.fit_transform(
    public_test[['Campaign_Code']]
    )

In [96]:
X_public = public_test.drop('Converted', axis=1)
y_public = public_test['Converted']

y_pred_public = lr.predict(X_public)

from sklearn.metrics import f1_score

print(f1_score(y_public, y_pred_public))

0.5426857406552839

In [225]:
public_test

,Income,City_Tier,Discount_Seen,Browser_Version,Campaign_Code,Converted,Engagement_Score,previous_customer,Device_Traffic_DesktopOrganic,Device_Traffic_DesktopPaidAds,...,Device_Traffic_MobileOrganic,Device_Traffic_MobilePaidAds,Device_Traffic_MobileReferral,Device_Traffic_MobileSocialMedia,Device_Traffic_TabletEmail,Device_Traffic_TabletOrganic,Device_Traffic_TabletPaidAds,Device_Traffic_TabletReferral,Device_Traffic_TabletSocialMedia,Age
0,-0.222592,3,0,13,0.075418,1,-0.059780,1,0,0,...,0,0,0,0,0,1,0,0,0,0.643405
1,-1.201519,1,1,10,0.586665,0,0.078206,1,0,0,...,0,1,0,0,0,0,0,0,0,-0.210776
2,-1.152908,3,0,21,1.074939,1,-0.328833,1,0,0,...,1,0,0,0,0,0,0,0,0,0.022183
3,3.051814,3,0,9,0.034144,0,-0.590584,1,0,0,...,0,0,0,0,0,0,0,0,0,-1.530873
4,-1.360283,1,1,9,-0.535898,0,-1.020685,1,0,0,...,0,0,0,1,0,0,0,0,0,0.410447
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,-0.170976,2,1,5,0.187947,1,-0.223134,1,1,0,...,0,0,0,0,0,0,0,0,0,0.177488
2996,1.302130,3,1,16,-0.271513,0,-1.193648,1,1,0,...,0,0,0,0,0,0,0,0,0,0.022183
2997,-0.006030,1,0,8,1.134902,0,-0.163942,1,0,0,...,0,0,0,0,0,0,0,0,1,0.565752
2998,0.486872,3,1,8,-0.921377,0,-0.751632,1,0,0,...,0,0,0,0,1,0,0,0,0,0.099836
2999,0.187238,1,1,7,-1.278432,1,-0.338827,1,0,0,...,0,0,0,0,0,1,0,0,0,1.264627

In [97]:
private_pred=lr.predict(private_test)

In [99]:
submission = pd.DataFrame({
    'Converted': private_pred,
    'User_ID': private_test['User_ID']
})

submission.to_csv('submission.csv', index=False)